proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: admin
  # Example: 'simple' authentication configuration
  users:
    - name: ${USER1_NAME}
      password: ${USER1_PASSWORD}
      groups: [ admin, user ]
    - name: ${USER2_NAME}
      password: ${USER2_PASSWORD}
      groups: [ user ]
  docker:
    url: http://127.0.0.1:2375
    port-range-start: 3838
  specs:
    - id: pcapp
      display-name: PCApp
      description: Principal component analysis with time series
      container-cmd: ["R", "-e", "PCApp::run_app()"]
      container-image: justusweyers/pcapp:latest
      container-network-connections: [ "app_network" ]
      access-groups: [ admin, user]
      container-env-file: .env
      container-env:
        DBIP: ${DBIP}
