name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  # publish_image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3
  #     - name: build
  #       run: 
  #         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pcapp:latest .
  #     - name: login
  #       run:
  #         docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: push
  #       run:
  #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/pcapp:latest

  deploy_webapp:
    # needs: [publish_image]
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # - name: create environment
      #   run: echo 'PORT={{ secrets.PORT }}' > .env
      # - name: create application properties
      #   run: echo 'PORT={{ secrets.PORT }}' > application.properties
      # - name: pull webapp
      #   run: docker pull justusweyers/pcapp:latest
      - name: copyjob
        run: echo '{{ secrets.SUDO }}' | sudo -S cp testi.txt /home/root/testi.txt 
      - name: namespace
        run: chown root:root /home/root/testi.txt
      - name: restart shinyproxy
        run: echo '{{ secrets.SUDO }}' | sudo -S service shinyproxy restart
      - name: clean up
        run: history -c
