name: Publish image to Docker Hub
on:
  [push]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: 
          docker build -t justusweyers/pcapp:latest .
      - name: login
        run:
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: publish
        run:
          docker push justusweyers/pcapp:latest
